name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild clean build analyze test -scheme Cointivity -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'

  
