name: Xcode - Build and Analyze

on:
  push:
    branches: [ "test/workflow" ]
  pull_request:
    branches: [ "test/workflow" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          xcodebuild clean build analyze -scheme Cointivity -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15'

  
